# Generated by Django 4.1.3 on 2022-11-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия, Имя')),
                ('sex', models.CharField(choices=[('М', 'Муж'), ('Ж', 'Жен')], max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вещи')),
                ('individual', models.BooleanField(verbose_name='Индивидуальные')),
                ('common', models.BooleanField(verbose_name='Общие')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['common'],
            },
        ),
        migrations.CreateModel(
            name='ThingsOfRaftingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.members', verbose_name='id Участника')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.things', verbose_name='id Вещи')),
            ],
        ),
        migrations.CreateModel(
            name='Rafting_23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название реки')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('content', models.TextField(verbose_name='Описание сплава')),
                ('km_on_river', models.IntegerField(verbose_name='Километров по реке')),
                ('km_from_perm', models.IntegerField(verbose_name='Километров от Перми')),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('level', models.CharField(choices=[('Лёг', 'Лёгкая'), ('Ср', 'Средняя'), ('Тяж', 'Тяжёлая')], max_length=30, verbose_name='Сложность')),
                ('members', models.ManyToManyField(to='rafting.members')),
            ],
            options={
                'verbose_name': 'Сплав',
                'verbose_name_plural': 'Сплавы',
                'ordering': ['days', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('rafting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rafting.rafting_23', verbose_name='id Сплава')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['rafting_id'],
            },
        ),
    ]
