# Generated by Django 4.1.3 on 2022-11-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия, Имя')),
                ('sex', models.CharField(choices=[('М', 'Муж'), ('Ж', 'Жен')], max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rafting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название реки')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('content', models.TextField(verbose_name='Описание сплава')),
                ('km_on_river', models.IntegerField(verbose_name='Километров по реке')),
                ('km_from_perm', models.IntegerField(verbose_name='Километров от Перми')),
                ('title_image', models.ImageField(blank=True, upload_to='images/')),
                ('preview_image', models.ImageField(blank=True, upload_to='images/')),
                ('level', models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Средняя', 'Средняя'), ('Тяжелая', 'Тяжёлая')], max_length=30, verbose_name='Сложность')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('members', models.ManyToManyField(blank=True, to='rafting.members')),
            ],
            options={
                'verbose_name': 'Сплав',
                'verbose_name_plural': 'Сплавы',
                'ordering': ['days', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RaftingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(blank=True, to='rafting.members')),
                ('rafting', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='rafting.rafting', verbose_name='Сплав')),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вещи')),
                ('individual', models.BooleanField(verbose_name='Индивидуальные')),
                ('common', models.BooleanField(verbose_name='Общие')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['common'],
            },
        ),
        migrations.CreateModel(
            name='ThingsOfRaftingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.raftingmembers', verbose_name='id Участника сплава')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.things', verbose_name='id Вещи')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('rafting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rafting.rafting', verbose_name='id Сплава')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['rafting_id'],
            },
        ),
    ]
