# Generated by Django 4.1.3 on 2022-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='things',
            options={'ordering': ['individual'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.RemoveField(
            model_name='things',
            name='common',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/basic'),
        ),
        migrations.AlterField(
            model_name='rafting',
            name='members',
            field=models.ManyToManyField(blank=True, to='rafting.members', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='rafting',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='images/preview/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='rafting',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='images/title/', verbose_name='Главное фото'),
        ),
    ]
