# Generated by Django 4.1.3 on 2022-11-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafting', '0002_alter_things_options_remove_things_common_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30, verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('rafting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rafting.rafting', verbose_name='Сплав')),
            ],
            options={
                'verbose_name': 'Тайминг',
                'verbose_name_plural': 'Тайминги',
                'ordering': ['time'],
            },
        ),
    ]
