# Generated by Django 4.1.3 on 2022-12-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия, Имя')),
                ('sex', models.CharField(choices=[('М', 'Муж'), ('Ж', 'Жен')], max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rafting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название реки')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('content', models.TextField(verbose_name='Описание сплава')),
                ('km_on_river', models.IntegerField(verbose_name='Километров по реке')),
                ('km_from_perm', models.IntegerField(verbose_name='Километров от Перми')),
                ('title_image', models.ImageField(blank=True, upload_to='images/title/', verbose_name='Главное фото')),
                ('preview_image', models.ImageField(blank=True, upload_to='images/preview/', verbose_name='Превью')),
                ('level', models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Средняя', 'Средняя'), ('Тяжелая', 'Тяжёлая')], max_length=30, verbose_name='Сложность')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('members', models.ManyToManyField(to='rafting.members')),
            ],
            options={
                'verbose_name': 'Сплав',
                'verbose_name_plural': 'Сплавы',
                'ordering': ['days', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вещи')),
                ('individual', models.BooleanField(verbose_name='Индивидуальные')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['individual'],
            },
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30, verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('rafting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.rafting', verbose_name='id сплава')),
            ],
            options={
                'verbose_name': 'Тайминг',
                'verbose_name_plural': 'Тайминги',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ThingsOnRaftings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField()),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rafting.members')),
                ('rafting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.rafting')),
                ('thing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafting.things')),
            ],
            options={
                'verbose_name': 'Вещь на сплаве',
                'verbose_name_plural': 'Вещи на сплаве',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/basic')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('rafting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rafting.rafting', verbose_name='id Сплава')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['rafting_id'],
            },
        ),
    ]
